### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by chDame** [camunda-community-hub/camunda-custom-operation-tools#8]
Hi @camunda-community-hub/devrel,

could you rename that project as camunda-custom-operation-tools to avoid confusion with Operate ?

Thanks in advance,

Christophe

**Comment by berndruecker** [comment]
[x] done - as far as I see it is not yet added to https://github.com/camunda-community-hub/infrastructure/blob/master/terraform/github/repositories.tf so we need not to update the name there
